name: Build and Publish Docker Image

on:
push:
branches:
- main # Déclenche le workflow sur un push sur la branche main
tags:
- 'v*' # Déclenche le workflow uniquement sur les tags versionnés (par exemple "v1.0", "v1.1")

jobs:
build:
runs-on: ubuntu-latest # Utilisation d'un runner Ubuntu

steps:
# Vérifier le code du dépôt
- name: Checkout code
uses: actions/checkout@v3

# Configurer Docker
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2

# Se connecter à Docker Hub
- name: Log in to Docker Hub
uses: docker/login-action@v2
with:
username: ${{ secrets.DOCKER_USERNAME }} # Ajoute tes identifiants Docker Hub dans les secrets GitHub
password: ${{ secrets.DOCKER_PASSWORD }}

# Construire l'image Docker et taguer avec le tag Git
- name: Build and push Docker image
uses: docker/build-push-action@v3
with:
context: . # Contexte de la construction (répertoire courant)
push: true # Pousse l'image vers Docker Hub
tags: ${{ secrets.DOCKER_USERNAME }}/mon_image:${{ github.ref_name }} # Tag l'image avec le nom du tag Git

# Optionnel : nettoyer les anciennes images locales sur Docker Hub pour garder l'espace propre
- name: Clean up unused images
run: docker image prune -f

